name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Build WASM
        run: |
          GOOS=js GOARCH=wasm go build -o static/main.wasm ./cmd/web
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" static/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
